id: SetTemplateLink
key: SetTemplateLink
name: Set Template Link
version: 1.0
description: SetTemplateLink
author_name: <__trans phrase="_PLUGIN_AUTHOR">
author_link: http://weblibrary.s224.xrea.com/weblog/
doc_link: https://github.com/coolniikou/mt-plugin-SetTemplateLink 

blog_config_template: set_template_path.tmpl

settings:
    set_template_path:
        scope: blog

applications:
    cms:
        page_actions:
            list_templates:
                set_linkedfile_templates:
                    label: SetLinkdFileTemplates
                    order: 1000
                    permit_action: administers
                    condition: $SetTemplateLink::SetTemplateLink::Plugin::can_use_set
                    mode: set_linkedfile_templates
                    dialog: 1
        methods:
            set_linkedfile_templates: $SetTemplateLink::SetTemplateLink::Plugin::hdlr_set_linkedfile_templates

callbacks:
    MT::App::CMS::template_param.edit_template: $SetTemplateLink::SetTemplateLink::Transformer::hdlr_template_param_edit_template
    MT::App::CMS::template_source.edit_template: $SetTemplateLink::SetTemplateLink::Transformer::hdlr_template_source_edit_template
    MT::App::CMS::template_source.list_common: $SetTemplateLink::SetTemplateLink::Transformer::hdlr_template_source_list_common
